// export const brunswick_hero = '/images/brunswick/lake_george.jpg'
export const brunswick_hero = '/images/brunswick/exterior.jpg'
export const brunswick_section2 = '/images/brunswick/mountain.jpg'
export const brunswick_room_a1 = '/images/brunswick/room-a-1.jpg'
export const brunswick_room_a2 = '/images/brunswick/room-a-2.jpg'
export const brunswick_room_a3 = '/images/brunswick/room-a-3.jpg'
export const brunswick_room_a4 = '/images/brunswick/room-a-4.jpg'

export const brunswick_logo = '/images/brunswick/logo.png'
export const brunswick_logo_dark = '/images/brunswick/logo_dark.png'

export const ug_logo = '/images/unionGables/logo.png'
export const ug_logo_dark = '/images/unionGables/logo_dark.png'
export const ug_hero = '/images/unionGables/exterior.jpg'
export const ug_video = '/images/unionGables/video.webp'
export const ug_racetrack = '/images/unionGables/racetrack.jpg'
export const ug_garden = '/images/unionGables/garden.jpg'