export default {
  aboutUs: '/about-us',
  blogs: '/blogs',
  breakfast: '/breakfast',
  carriageHouse: '/carriage-house',
  contact: '/contact',
  dining: '/dining',
  gallery: '/gallery',
  giftCertificates: '/gift-certificates',
  explore: '/explore',
  home: '/',
  location: '/location',
  lodging: '/lodging',
  mainMansion: '/main-mansion',
  petFriendly: '/pet-friendly',
  promotions: '/promotions',
  reservationPolicies: '/reservation-policies',
  resNexus: 'https://resnexus.com/resnexus/reservations/book/E56DE62E-3D4B-487A-AD23-2037884AF770/?NewSearch=1',
  reviews: '/reviews',
  sacredUnion: '/sacred-union',
  saratogaEvents: '/events',
  saratogaPerformingArts: '/performing-arts-center',
  saratogaRaceCourse: "/race-course",
  saratogaSprings: '/springs-city-center',
  skidmoreCollege: '/skidmore-college',
  spa: '/spa',
  spaStatePark: '/spa-state-park'
}
